### ISSUE TITLE
The bot not working when creating an issue

### ISSUE THREAD

**Issue by Alanwang2015** [riyadhalnur/issuelabeler#31]
**Describe the bug**
Please check my project: https://github.com/Alanwang2015/Issue-Labeler-Bot/issues/8#issue-653260601
I have installed the bot for my repo, but it didn't work.

**Comment by riyadhalnur** [comment]
The title and/or body needs to contain a word from the list of labels in your repo.

**Comment by Alanwang2015** [comment]
Thanks!
