### ISSUE TITLE
Limiting the number of labels to consider is the wrong default

### ISSUE THREAD

**Issue by ftrotter** [riyadhalnur/issuelabeler#33]
**Describe the bug**
The default setting for the robot should be to get all of the labels to compare with the issue title, not just 20.
This creates a dangerous solution where you get very strange results when you are using the robot successfully with 1 labels and then you add 4 labels and suddenly, the robot will not consider labels 21 and 22. 

Instead the robot should default to downloading "all" labels and only worry about limiting the number of labels if that is configured. 

I cannot think of a use case where you might have 45 labels but you would only want this functionality for 20 of them... especially if you cannot choose which 20 you want to use in this manner.

**To Reproduce**
n/a

**Expected behavior**
I would expect that the robot would always get all of the labels, rather than just twenty, and then IF there is a limit set in the yaml file... then and only then would the robot limit itself. 

**Screenshots**
n/a

**Desktop (please complete the following information):**
n/a

**Smartphone (please complete the following information):**
n/a

**Additional context**
n/a

**Comment by riyadhalnur** [comment]
Latest version v2.2.0 now fallbacks to the max 100 (github api limit) for number of labels to fetch if not specified in the config
